[build]
  command = "npm run build"
  publish = "build"

[context.production.environment]
  REACT_APP_API_URL = "https://react-bookstore-backend-652a0deaa7fb.herokuapp.com/api/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
